# Generated by Django 5.1.1 on 2024-10-23 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_servicio', models.CharField(max_length=100)),
                ('categoria', models.CharField(max_length=50)),
                ('subcategoria', models.CharField(blank=True, max_length=100, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=300, null=True)),
                ('precio_anterior', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('descuento', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('precio_oferta_actual', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fecha_promocion_inicio', models.DateField(blank=True, null=True)),
                ('fecha_promocion_final', models.DateField(blank=True, null=True)),
                ('horario', models.CharField(blank=True, max_length=100, null=True)),
                ('nombre_encargado', models.CharField(blank=True, max_length=100, null=True)),
                ('video1', models.CharField(blank=True, max_length=255, null=True)),
                ('video2', models.CharField(blank=True, max_length=255, null=True)),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo')], default='ACTIVO', max_length=8)),
            ],
        ),
    ]
