# Generated by Django 5.1.1 on 2024-10-28 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicio',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='servicio',
            name='fecha_promocion_final',
        ),
        migrations.RemoveField(
            model_name='servicio',
            name='fecha_promocion_inicio',
        ),
        migrations.RemoveField(
            model_name='servicio',
            name='horario',
        ),
        migrations.RemoveField(
            model_name='servicio',
            name='nombre_encargado',
        ),
        migrations.RemoveField(
            model_name='servicio',
            name='video1',
        ),
        migrations.RemoveField(
            model_name='servicio',
            name='video2',
        ),
    ]
